### DISCUSSION TITLE
osu!lazer terminates mate-panel

### DISCUSSION THREAD

**Discussion by Oreoezi** [ppy/osu#20786] [Q&A]
### Type

Other

### Bug description

After launching the game for the first time I was confused as to why my panel was not showing up. I turned it back on by launching it through the terminal using the `mate-panel` command. After reopening the game the process got killed and the only thing it printed inside the terminal was `Terminated`. I assume this was made so the panel wouldn't render on top of the game, but it would be nice if it at least reopened it when you closed the game or tabbed out of it. Logs are irrelevant but it was mandatory.

### Version

2022.1008.2

### Logs

touch: cannot touch 'home/user/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory

**Comment by bdach** [comment]
The game is not supposed to be "terminating" anything on its own.

This may very well be a driver issue, or a mate-panel issue. I can't tell for sure just from a "terminated" prompt. We'd at least need more detail about *why* mate-panel terminates, in some shape or form. Debug logs from mate-panel, or something.

**Reply by Oreoezi** [reply]
gdb does not help in providing info. `bt` outputs `No Stack`. Two things worth noting:
1. I run my game at 1920x1080, which is not my native resolution as this laptop has a weirder aspect ratio
2. Running `osu.AppImage` from the terminal launches it in a small window, whilst running it from a `.desktop` launches it in fullscreen. (even though it is supposed to be completely identical)

This is my `osu!.desktop` file:

```toml
[Desktop Entry]
Name=osu!Lazer
Comment=Rhythm is just a click away!
GenericName=osu
Exec=/usr/bin/osu.AppImage
Type=Application
StartupNotify=false
Categories=Game;
Keywords=osu!;taiko;mania;ctb
Icon=lazer
```
