### ISSUE TITLE
Linux AppImage is not able to update anymore since 2022.723.0

### ISSUE THREAD

**Issue by Diyou** [ppy/osu#19780]
### Type

Other

### Bug description

> Something I wanted to note is that since the initial PR I could not manage to update to any new release with any external tool or this code due to missing public keys.
> 2022.731.1 seems to be signed but lacks the detached signature which results in a failed validation.
> 2022.709.1 was the last release I can conduct a successful update.

Mentioned in #19167

Can be reproduced with a ```docker-compose.yml```
```yaml
version: '3'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: osu.AppImage-Update.Test
    privileged: true
    command:
      - /bin/bash
      - -c
      - |
        apt-get update
        apt-get install -y wget
        apt-get install -y libfuse-dev
        apt-get install -y gnupg2
        wget -O osu.AppImage https://github.com/ppy/osu/releases/download/2022.723.0/osu.AppImage
        wget -O appimageupdatetool.AppImage https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage && chmod +x ./appimageupdatetool.AppImage
        ./appimageupdatetool.AppImage osu.AppImage
```
And run with ```docker compose up```

### Version

Since 2022.723.0

### Logs

until 2022.723.0
```bash
osu.AppImage-Update.Test  | /usr/bin/gpg2: gpg: Signature made Fri Jul 22 18:17:35 2022 UTC
osu.AppImage-Update.Test  | /usr/bin/gpg2: gpg:                using RSA key 12FFFB66DFE66662DAAA22288CED17CA117D6549
osu.AppImage-Update.Test  | /usr/bin/gpg2: gpg: Good signature from "Dean Herbert (ppy) <pe@ppy.sh>" [unknown]
osu.AppImage-Update.Test  | /usr/bin/gpg2: gpg: WARNING: This key is not certified with a trusted signature!
osu.AppImage-Update.Test  | /usr/bin/gpg2: gpg:          There is no indication that the signature belongs to the owner.
osu.AppImage-Update.Test  | /usr/bin/gpg2: Primary key fingerprint: 12FF FB66 DFE6 6662 DAAA  2228 8CED 17CA 117D 6549
```
later:
```bash
osu.AppImage-Update.Test  | /usr/bin/gpg2: gpg: not a detached signature
osu.AppImage-Update.Test  | Validation error: Bad signature
osu.AppImage-Update.Test  | Restoring original file
osu.AppImage-Update.Test exited with code 1
```
